[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "file"]  # "file" provides libmagic

[phases.build]
cmds = [
    "python3.12 -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "MAGIC_LIBRARY=$(nix eval --raw nixpkgs#file)/lib/libmagic.so uvicorn main:app --host 0.0.0.0 --port $PORT"
